### ISSUE TITLE
AddData.ipynb /tmp/ directory's name could be changed

### ISSUE THREAD

**Issue by batukav** [NMRLipids/NMRlipidsIVPEandPG#26]
Hello @akiirik and @ohsOllila ,

In the current version of the AddData.ipynb the output files are initially written to a '/tmp/' directory. This is fine, however if I try to run multiple instances of the notebook for the different trajectories (because I have many to analyze at the moment), the other instances cannot proceed because all the files from different trajectories are written into the '/tmp/' directory. Would you consider giving it a rather unique name (something like tmp_6-DIGIT-RANDOM-INTEGER) so that whenever we have multiple instances running they all can continue without any conflicts?

**Comment by ohsOllila** [comment]
We have now a new version of the databank building script which is python code instead of notebook: 
 https://github.com/NMRLipids/NMRlipidsIVPEandPG/blob/master/scripts/DataBankINFO/AddData.py

It locates in folder https://github.com/NMRLipids/NMRlipidsIVPEandPG/tree/master/scripts/DataBankINFO
and can be ran as: 
ipython3 AddData.py [FILENAME]
where filename contains user given information on the system to be added. Examples, such as POPEcharmmINFO.py, can be found from the folder.

I have fixed this issue into that code. It makes as @batukav proposed. Please test and close the issue if works for you.

**Comment by batukav** [comment]
Thanks @ohsOllila ! It's working as intended. I'm closing the issue.
